### PR TITLE
Bot prefix change

### PR DESCRIPTION
**Pull request by arock475**
Added a check to make sure that "<" is not able to be a bot prefix. This prefix causes any mention of a user to be confused as a command and throw an error.

### CODE REVIEW

**Review by jkriste — CHANGES_REQUESTED** [review]
Looks good, however, this doesn't stop users from setting it via the custom prefix command. I would suggest creating a list of disallowed prefixes somewhere and using that to check against on startup as well as on prefix set.

**Comment by arock475** [comment]
Would the consts file be a fine place for it?

**Comment by jkriste** [comment]
> Would the consts file be a fine place for it?

Yes, but instead of creating a class for it, just place it below the regex var, like so:
```py
TAG_INVOKE_REGEX = r"{tag_prefix}([^\s]+)"
INVALID_PREFIXES = ["<"]
```

One last slight change I would make [here](https://github.com/ClemBotProject/ClemBot/pull/871/files#diff-42c96e3624131f643dc2278ce992cd650a4df5cd95806dc54f713fdafe7a8c94R52) is changing the message to be something like...
<code>The given prefix &#96;&lt;prefix&gt;&#96; is not supported.</code>

**Comment by arock475** [comment]
Made the requested changes!

**Review by jkriste — APPROVED** [review]
lgtm 🎉

**Pull request merged**
