### PR TITLE
Fixed spongebob command

### LINKED ISSUE #778: Improve !spongebob command
Currently the !spongebob command just has a ~40% chance for each character to be uppercase/~60% chance to be lowercase (regardless of the original case). However, this often makes strings that don't quite capture the feel of the actual spongebob text meme.

Possible solutions:
-Use a more uniform distribution of capital letters
-Alternate small, random length runs of characters with the same case
-any more suggestions? Will update issue with more as suggested.

### PR DESCRIPTION
**Pull request by xcelr8**
fixes #778 
```py
result = ''.join(choice((str.upper, str.lower))(char) for char in args)
```
explanation: choice() picks a random item from the tuple of (str.upper, str.lower) and applies to each character in the string which are then joined together

### CODE REVIEW

**Comment by Jay-Madden** [comment]
@xcelr8 you don't have to close the PR, fix the errors and just commit the fix and push it, the PR will automatically Revalidate the code

**Comment by xcelr8** [comment]
@Jay-Madden This is basically my first contribution, I don't understand the error and how to setup the whole env yet. Thought the little bit of python code would be enough. Maybe I'll share the idea in the issue thread itself.

**Comment by Jay-Madden** [comment]
Thats fine, this feature can be done with botonly mode enabled, follow the [https://github.com/ClemBotProject/ClemBot/blob/master/CONTRIBUTING.md](Contributing.md) file to get it setup, its very simple. Drop a question in #bot-dev-discussion if you have any questions.

**Comment by xcelr8** [comment]
I think the error might be importing random and using choice directly instead of random.choice in the code as when I coded it I imported choice directly.

**Comment by xcelr8** [comment]
- Left the code for totally random UC/LC as a comment
- Applied the code for alternating short random spans of UC/LC

**Comment by jkriste** [comment]
The `spongebob` command has been moved to [SockBot](https://github.com/Jay-Madden/SockBot), so if you would still like to fix the issue, you are more than welcome to open a PR there.

**Pull request closed without merging**
